### ISSUE TITLE
Setting up a Gauge with labels causes `set_to_current_time()` to complain

### ISSUE THREAD

**Issue by aanastasiou** [prometheus/client_python#561]
Hello

I am trying to set up a Gauge with labels but this causes `set_to_current_time()` to fire an error. When the Gauge is setup without labels, the whole thing works as expected. 

I am setting up the Gague as follows:

```
some_gauge = prometheus_client.Gauge("some_parameter", 
                                      "An instantaneous parameter",
                                      labelnames = ("dim1","dim2","dim3"),
                                      namespace="somens",
                                      unit="some_unit")

...
...
...
```

And at the point of updating its instantaneous value:

```
some_gauge.set_to_current_time()
some_gauge.labels("Alpha", "Beta", "Gamma").set(current_gauge_value)
```

This fails with:

```
...
self._value.set(float(value))
AttributeError: 'Gauge' object has no attribute '_value'
```

That is, it does not even get to the point where the server is raised so that Prometheus can connect to it.

If however I define the gauge as:

```
some_gauge = prometheus_client.Gauge("some_parameter", 
                                      "An instantaneous parameter")
```

Everything works as expected. The point is, I need to add the labels along with the measurement as well.

Working in Ubuntu 20.04(Linux 5.3.0-1028-azure x86_64), Python 3.8, prometheus, version 2.7.1+ds (branch: debian/sid, revision: 2.7.1+ds-3), prometheus-client version 0.8.0

Any ideas?
